### ISSUE TITLE
Returning elevation 0

### ISSUE THREAD

**Issue by strymsg** [Developer66/open-elevation#16]
Hi, i just setup up the application with python virtualenv, then `./create-dataset.sh` (which downloaded data to up about 4.6 GB) then run it with `python server.py` but when using the api the elevation returns always 0.
```
{"results": [{"latitude": 10.0, "longitude": 10.0, "elevation": 0}, {"latitude": 20.0, "longitude": 20.0, "elevation": 0}, {"latitude": 54.161758, "longitude": -54.583933, "elevation": 0}]}
{"results": [{"latitude": 10.0, "longitude": 10.0, "elevation": 0}, {"latitude": 20.0, "longitude": 20.0, "elevation": 0}, {"latitude": 55.161758, "longitude": -55.583933, "elevation": 0}]}
```
After initializing and doing requests it is shown on the app console:
```
[2020-05-06 11:09:22 -0400] [4173] [INFO] Booting worker with pid: 4173                                                            
No module named '_gdal_array'                                           
No module named '_gdal_array'  
```
And also these messages when shutting down:
```
[2020-05-06 11:10:26 -0400] [4164] [INFO] Shutting down: Master
Exception ignored in: <bound method Handle.__del__ of <rtree.index.PropertyHandle object at 0x7f19a4445d30>>
Traceback (most recent call last):
  File "/home/testr/openelevation/open-elevation/venv/lib/python3.5/site-packages/rtree/index.py", line 875, in__del__                       
  File "/home/testr/openelevation/open-elevation/venv/lib/python3.5/site-packages/rtree/index.py", line 864, indestroy                       
  File "/home/testr/openelevation/open-elevation/venv/lib/python3.5/site-packages/rtree/core.py", line 34, in check_void_done                
AttributeError: 'NoneType' object has no attribute 'Error_GetErrorCount'
Exception ignored in: <bound method Handle.__del__ of <rtree.index.IndexHandle object at 0x7f19a2b26da0>>
Traceback (most recent call last):
  File "/home/testr/openelevation/open-elevation/venv/lib/python3.5/site-packages/rtree/index.py", line 875, in__del__                       
  File "/home/testr/openelevation/open-elevation/venv/lib/python3.5/site-packages/rtree/index.py", line 864, indestroy                       
  File "/home/testr/openelevation/open-elevation/venv/lib/python3.5/site-packages/rtree/core.py", line 34, in check_void_done                
AttributeError: 'NoneType' object has no attribute 'Error_GetErrorCount'
```

Is this because data source changed?, thanks in advance :)

**Comment by Developer66** [comment]
Seems:

1. Coords not in the datasheet
2. A dependency is missing
